const dayOneData = [
    {
        id: 1,
        name: "RoboRace",
        imgSrc: "#",
        heading: "Robo Race",
        venue: "Infront of Gauri Cafe",
        headingPara: "A Robo Race is a thrilling competition where autonomous robots navigate a track, showcasing their speed and agility while tackling obstacles. Participants program these machines to race independently, demonstrating cutting-edge technology and innovation in robotics.",
        rules: [
            "1. Design a manually controlled ROBOT that has capacity to cover maximum distance in shortest possible time, challenging the hurdles and be one of the best opponents. ",
            "2. The maximum dimension of the robot can be 350 x 350 mm (L x B).",
        ],
        judgingCriteria: [
            "Time constraint will be set",
            "Accuracy"
        ],
        spocDetails: '',
        paymentLink: "",
        redirectLink: "/Day1/RoboRace",
    },
    {
        id: 6,
        name: "CodingBees",
        imgSrc: "#",
        heading: "Coding Bee's",
        venue: "TBD",
        headingPara: "Calling all coding enthusiasts! Are you ready to tackle some tricky coding challenges and prove your debugging expertise? Join us for Coding Bee's, a thrilling event at our college Tech Fest where you'll identify and fix errors in code. Put your coding prowess to the test and emerge as the ultimate debugging champion!",
        rules: [
            "1. Teams must consist of 2 members.",
            "2. Participants must bring their own laptops.External devices, except for keyboards and mice, are not allowed.",
            "3. Participants must refrain from using external code or resources during the competition.",
            "4. Participants will be provided with a digital copy of the code to debug.",
            "5. Teams must submit their debugged code within the specified time frame. Late submissions may incur penalties.",
            "6. Any form of cheating, plagiarism, or unauthorized collaboration will result in disqualification.",
            "7. Any disputes or concerns must be raised with event organizers promptly. Organizers' decisions are final.",
        ],
        judgingCriteria: [
            "Accuracy: Correctly identify and fix all errors in the code.",
            "Efficiency: Solve the problems quickly and efficiently.",
            "Code Quality: Produce clean, well-structured, and maintainable code.",
            "Creativity: Identify potential improvements or optimizations in the code.",
        ],
        spocDetails: '',
        paymentLink: "",
        redirectLink: "/Day1/CodingBees",
    },
    {
        id: 7,
        name: "ESummit",
        imgSrc: "#",
        heading: "E-Summit",
        venue: "TBD",
        headingPara: "Come to our Tech Pravaah E-Summit and experience an exciting voyage of innovation and business acumen! Join forces with trailblazing businesspeople, industry veterans, and visionaries who have had a lasting impact on the entrepreneurial scene at this iconic event. The E-Summit promises a day of engaging keynote talks, stimulating panel discussions, and immersive workshops set against the backdrop of our College Tech Fest.",
        rules: [

        ],
        judgingCriteria: [

        ],
        spocDetails: '',
        paymentLink: "",
        redirectLink: "/Day1/ESummit",
    },
    {
        id: 8,
        name: "Workshop",
        imgSrc: "#",
        heading: "Work-shop",
        venue: "TBD",
        headingPara: [
            "1. Virtual Reality Workshop : Step into the future with our Virtual Reality Workshop! Explore the cutting-edge technology of VR and learn to create immersive experiences. From gaming to education, discover the diverse applications of VR and gain hands-on experience in developing your own virtual worlds. This workshop will demystify the complexities of VR, offering a comprehensive overview of its principles and potential. Immerse yourself in a dynamic learning environment where creativity meets technology, and leave with the skills to shape the digital landscapes of tomorrow.",
            "2. Ethical Hacking Workshop : Embark on a journey into the world of cybersecurity with our Ethical Hacking Workshop. Uncover the methodologies and tools ethical hackers use to identify and fortify digital defenses. From penetration testing to vulnerability assessment, participants will gain practical insights into securing systems and networks. This workshop is designed to equip you with essential skills in ethical hacking, emphasizing the importance of responsible and lawful practices in the ever-evolving landscape of cybersecurity.",
            "3. Internet Of Things (IOT) Workshop : Delve into the interconnected world of IoT at our workshop. Gain a comprehensive understanding of the Internet of Things, from its foundational concepts to hands-on project development. Participants will learn to create innovative IoT solutions applicable to various domains, fostering a deeper appreciation for the transformative power of connected devices. Join us to explore the limitless possibilities and practical applications of IoT, and leave with the knowledge to contribute to the growing field of smart technology.",
            "4. Prompt Writing Workshop : Unleash your creativity in our Prompt Writing Workshop! Dive into the art of crafting compelling narratives in response to prompts across genres. From fiction to non-fiction, participants will refine their writing skills through engaging exercises and collaborative discussions. This workshop aims to enhance the ability to think on your feet and produce impactful written content under time constraints. Whether you're an aspiring writer or simply eager to explore the world of prompt-based creativity, this workshop promises an enriching experience that will leave you inspired and equipped with new tools for effective expression.",
            "5. Finance Awareness Workshop : Navigate the intricacies of finance in our Finance Awareness Workshop. From fundamental concepts to practical applications, participants will gain insights into personal finance, investment strategies, and the broader economic landscape. This workshop aims to empower individuals with financial literacy, enabling them to make informed decisions in both personal and professional spheres. Join us to demystify the world of finance, foster a deeper understanding of economic trends, and acquire the knowledge necessary for financial success and security.",
            "6. Drone Workshop : Elevate your understanding of drone technology at our Drone Workshop. This hands-on experience will cover the principles of flight, navigation, and the diverse applications of drones in various industries. Participants will have the opportunity to pilot drones, explore their functionalities, and delve into the exciting realm of aerial innovation. Whether you're a novice or a drone enthusiast, this workshop caters to all levels of expertise. Come soar with us as we unravel the possibilities and intricacies of drone technology, providing you with the skills and knowledge to take flight in this dynamic field.",
        ],
        rules: [

        ],
        judgingCriteria: [

        ],
        spocDetails: '',
        paymentLink: "",
        redirectLink: "/Day1/Workshop",
    },
    {
        id: 9,
        name: "Hackathon",
        imgSrc: "#",
        heading: "Hack-a-thon",
        venue: "TBD",
        headingPara: "Gear up for a coding frenzy at our Tech Pravaah Hackathon, where creativity knows no limits! Taking place over 12 thrilling hours, this event invites coding enthusiasts of all levels to explore any theme that ignites their passion. We invite all passionate coders, tech enthusiasts, and problem solvers to join us for an exhilarating 12-hour coding extravaganza. The stage is yours, and the theme is open let your creativity run wild!",
        rules: [
            "1. Participants can register individually or as a team, with a maximum of 5 members per team.",
            "2. Respectful and inclusive behavior is expected from all participants. Any form of cheating, plagiarism, or unethical behavior will result in immediate disqualification.",
            "3. Teams must be formed before the start of the hackathon and can consist of members from different colleges. Team sizes should not exceed the specified limit of 5 members.",
            "4. The hackathon is open-themed, allowing participants to explore any area of technology or problem space.",
            "5. Projects must be original and not previously submitted to other competitions.",
            "6. Participants are required to bring their own laptops with the necessary development tools and software.",
            "7. Code must be written from scratch during the hackathon.",
            "8. All projects must be submitted by the designated deadline.",
            "9. Submissions should include a short project description, documentation, and a link to the working prototype.",
            "10. Projects will be evaluated based on the judging criteria outlined above.",
            "11. Judges' decisions are final and not subject to appeal.",
            "12. Participants retain ownership of their intellectual property.",
            "13. By participating, participants grant the event organizers the right to showcase their projects for promotional purposes.",
            "14. Any disputes or concerns must be raised with event organizers promptly. Organizers' decisions are final.",
            "15. Teams may be disqualified for violating the rules or code of conduct. Disqualified teams are not eligible for prizes.",
            "16. Prizes will be awarded to the top-performing teams based on the judging criteria.",
        ],
        judgingCriteria: [
            "Innovation (30 points)",
            "Technical Complexity (25 points)",
            "Functionality (20 points)",
            "User Experience (15 points)",
            "Presentation (10 points)",
            "Collaboration (Bonus Points)",
            "Code Quality (Bonus Points)",
        ],
        spocDetails: '',
        paymentLink: "",
        redirectLink: "/Day1/Hackathon",  
    },
]
export default dayOneData
